Drop Table Writes
Drop Table Borrows
Drop Table Reserves
Drop Table BOR_Transaction
Drop Table Reservation
Drop Table Copy
Drop Table Guest_Editor
Drop Table Proceedings
Drop Table Journal_Issue
Drop Table Journal_Volume
Drop Table Chief_Editor
Drop Table Book
Drop Table Author
Drop Table Branch
Drop Table Reader
Drop Table Document
Drop Table Publisher